// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
// first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence whose values do not exceed
// four million, find the sum of the even-valued terms.

#include <stdio.h>

#define LAST_VALUE 4000000

int main(void) {
    // Begin with first two Fibonacci numbers
    int x = 1;
    int y = 2;
    
    // Start the sum value at 2 to account for y's current value.
    int sum = 2;

    while (y < LAST_VALUE) {
        // Update x and y to point at next two numbers in sequence
        int next_fib = x + y;
        x = y;
        y = next_fib;

        // Only increment the sum if y is even
        if (y % 2 == 0) {
            sum += y;
        }
    }

    printf("The sum of all even Fibonacci numbers up to %d is: %d\n", LAST_VALUE, sum);
}

